# Generated by Django 6.0.2 on 2026-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('nationality', models.CharField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('medicallicencenumber', models.IntegerField(max_length=8)),
                ('specialization', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dateregistered', models.DateTimeField()),
                ('medicalhistory', models.TextField()),
            ],
        ),
    ]
