# Generated by Django 6.0.2 on 2026-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateregistered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
