# Generated by Django 6.0.2 on 2026-02-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_alter_patient_dateregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
