# Generated by Django 6.0.2 on 2026-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_myappointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
