# Generated by Django 6.0.2 on 2026-02-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0005_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactform',
            new_name='ContactMessage',
        ),
    ]
